In [1]:
import torch

In [17]:
rolling_window = 5
mid_frame = rolling_window // 2

inds_1 = torch.arange(0, rolling_window, 1)

if mid_frame % 2 == 0:
    inds_2 = torch.arange(0, rolling_window*2, 2)
else:
    inds_2 = torch.arange(1, rolling_window*2, 2)

if mid_frame % 3 == 0:
    inds_3 = torch.arange(0, rolling_window*3, 3)
elif mid_frame % 3 == 1:
    inds_3 = torch.arange(1, rolling_window*3, 3)
else:
    inds_3 = torch.arange(2, rolling_window*3, 3)

    

print('mid_frame: ', mid_frame)
print(inds_1)
print(inds_2)
print(inds_3)

mid_frame:  2
tensor([0, 1, 2, 3, 4])
tensor([0, 2, 4, 6, 8])
tensor([ 2,  5,  8, 11, 14])


In [18]:
rolling_window = 5
input_3 = [0, 3, 6, 9, 12]
input_2 = [2, 4, 6, 8, 10]
input_1 = [4,5,6,7,8]

print(input_1)
print(input_2)
print(input_3)

[5, 6, 7, 8, 9]
[3, 5, 7, 9, 11]
[1, 4, 7, 10, 13]


In [32]:
rolling_window = 7

inds_ind_3 = [i for i in range(0, 3*rolling_window, 3)]
ind_mid_frame = rolling_window // 2
base_mid_indice = inds_ind_3[ind_mid_frame]
print(base_mid_indice)

inds_ind_2 = [base_mid_indice +i for i in range(-rolling_window +1, rolling_window, 2)]
inds_ind_1 = [base_mid_indice +i for i in range(-rolling_window//2+1, rolling_window//2+1, 1)]

print(inds_ind_1)
print(inds_ind_2)
print(inds_ind_3)

9
[6, 7, 8, 9, 10, 11, 12]
[3, 5, 7, 9, 11, 13, 15]
[0, 3, 6, 9, 12, 15, 18]


In [43]:
range(-rolling_window//2, rolling_window//2+1, 1)

range(-2, 2)

In [1]:
len(range(2, 9))

7

In [33]:
files_per_key = {
    'O' : range(100),
    '1' : range(100),
}

base_mid_indice = 9

In [35]:
dict_input_3 = {key: [
            [ i + inds_ind_3[j] for j in range(rolling_window)] 
            for i in range(0, len(files_per_key[key]) - 2*base_mid_indice)
        ] for key in files_per_key.keys()}

In [37]:
dict_input_2 = {key: [
            [ i + inds_ind_2[j] for j in range(rolling_window)] 
            for i in range(0, len(files_per_key[key]) - inds_ind_2[-1])
        ] for key in files_per_key.keys()}

In [39]:
dict_input_1 = {key: [
            [ i + inds_ind_1[j] for j in range(rolling_window)] 
            for i in range(0, len(files_per_key[key]) - inds_ind_1[-1])
        ] for key in files_per_key.keys()}

In [40]:
dict_input_1

{'O': [[6, 7, 8, 9, 10, 11, 12],
  [7, 8, 9, 10, 11, 12, 13],
  [8, 9, 10, 11, 12, 13, 14],
  [9, 10, 11, 12, 13, 14, 15],
  [10, 11, 12, 13, 14, 15, 16],
  [11, 12, 13, 14, 15, 16, 17],
  [12, 13, 14, 15, 16, 17, 18],
  [13, 14, 15, 16, 17, 18, 19],
  [14, 15, 16, 17, 18, 19, 20],
  [15, 16, 17, 18, 19, 20, 21],
  [16, 17, 18, 19, 20, 21, 22],
  [17, 18, 19, 20, 21, 22, 23],
  [18, 19, 20, 21, 22, 23, 24],
  [19, 20, 21, 22, 23, 24, 25],
  [20, 21, 22, 23, 24, 25, 26],
  [21, 22, 23, 24, 25, 26, 27],
  [22, 23, 24, 25, 26, 27, 28],
  [23, 24, 25, 26, 27, 28, 29],
  [24, 25, 26, 27, 28, 29, 30],
  [25, 26, 27, 28, 29, 30, 31],
  [26, 27, 28, 29, 30, 31, 32],
  [27, 28, 29, 30, 31, 32, 33],
  [28, 29, 30, 31, 32, 33, 34],
  [29, 30, 31, 32, 33, 34, 35],
  [30, 31, 32, 33, 34, 35, 36],
  [31, 32, 33, 34, 35, 36, 37],
  [32, 33, 34, 35, 36, 37, 38],
  [33, 34, 35, 36, 37, 38, 39],
  [34, 35, 36, 37, 38, 39, 40],
  [35, 36, 37, 38, 39, 40, 41],
  [36, 37, 38, 39, 40, 41, 42],
  [37, 38, 39