In [30]:
from torchvision.io import read_image
from time import time

tens = read_image('/Data/reds_dataset/6.8300-Computer-Vision/data/raw/train_orig/000/00000001.png')
tens

# save this tensor as a png
from torchvision.utils import save_image
save_image(tens/255, 'test.png')

In [31]:
read_image('test.png')


tensor([[[220, 220, 220,  ...,  56,  46,  42],
         [220, 220, 220,  ...,  65,  48,  31],
         [219, 219, 219,  ...,  55,  36,  41],
         ...,
         [  6,   6,   6,  ..., 101, 100,  91],
         [  6,   6,   6,  ...,  99, 104,  92],
         [  6,   6,   6,  ..., 103, 110,  96]],

        [[237, 237, 237,  ...,  62,  52,  48],
         [237, 237, 237,  ...,  71,  54,  37],
         [236, 236, 236,  ...,  61,  42,  47],
         ...,
         [  7,   7,   7,  ..., 106, 105,  95],
         [  7,   7,   7,  ..., 102, 106,  94],
         [  7,   7,   7,  ..., 104, 111,  97]],

        [[253, 253, 253,  ...,  53,  43,  39],
         [253, 253, 253,  ...,  62,  45,  28],
         [252, 252, 252,  ...,  52,  33,  38],
         ...,
         [  9,   9,   9,  ...,  51,  49,  40],
         [  9,   9,   9,  ...,  47,  51,  39],
         [  9,   9,   9,  ...,  49,  56,  42]]], dtype=torch.uint8)

In [27]:
tens = read_image('/Data/reds_dataset/6.8300-Computer-Vision/data/processed/fimg/000/frame_0000.png')
tens

tensor([[[221, 221, 221,  ...,  43,  50,  41],
         [221, 221, 221,  ...,  53,  41,  36],
         [220, 220, 220,  ...,  56,  35,  35],
         ...,
         [  6,   6,   6,  ..., 107, 103,  81],
         [  6,   6,   6,  ..., 112, 108,  84],
         [  6,   6,   6,  ..., 112, 112,  88]],

        [[238, 238, 238,  ...,  49,  56,  47],
         [238, 238, 238,  ...,  59,  47,  42],
         [237, 237, 237,  ...,  62,  41,  41],
         ...,
         [  7,   7,   7,  ..., 110, 106,  84],
         [  7,   7,   7,  ..., 113, 109,  85],
         [  7,   7,   7,  ..., 113, 113,  89]],

        [[254, 254, 254,  ...,  40,  47,  38],
         [254, 254, 254,  ...,  50,  38,  33],
         [253, 253, 253,  ...,  53,  32,  32],
         ...,
         [  9,   9,   9,  ...,  54,  49,  28],
         [  9,   9,   9,  ...,  57,  53,  29],
         [  9,   9,   9,  ...,  57,  57,  33]]], dtype=torch.uint8)

In [24]:
import cv2

img = cv2.imread('/Data/reds_dataset/6.8300-Computer-Vision/data/raw/train_orig/000/00000001.png')
img.shape
# transpose img to be (C, H, W)
img = img.transpose(2, 0, 1)
print(img.shape)
img

(3, 720, 1280)


array([[[253, 253, 253, ...,  53,  43,  39],
        [253, 253, 253, ...,  62,  45,  28],
        [252, 252, 252, ...,  52,  33,  38],
        ...,
        [  9,   9,   9, ...,  51,  49,  40],
        [  9,   9,   9, ...,  47,  51,  39],
        [  9,   9,   9, ...,  49,  56,  42]],

       [[237, 237, 237, ...,  62,  52,  48],
        [237, 237, 237, ...,  71,  54,  37],
        [236, 236, 236, ...,  61,  42,  47],
        ...,
        [  7,   7,   7, ..., 106, 105,  95],
        [  7,   7,   7, ..., 102, 106,  94],
        [  7,   7,   7, ..., 104, 111,  97]],

       [[220, 220, 220, ...,  56,  46,  42],
        [220, 220, 220, ...,  65,  48,  31],
        [219, 219, 219, ...,  55,  36,  41],
        ...,
        [  6,   6,   6, ..., 101, 100,  91],
        [  6,   6,   6, ...,  99, 104,  92],
        [  6,   6,   6, ..., 103, 110,  96]]], dtype=uint8)

In [23]:
# transpose img to be (C, H, W)
img = img.transpose(2, 0, 1)
img.shape
img

array([[[253, 253, 253, ...,  53,  43,  39],
        [253, 253, 253, ...,  62,  45,  28],
        [252, 252, 252, ...,  52,  33,  38],
        ...,
        [  9,   9,   9, ...,  51,  49,  40],
        [  9,   9,   9, ...,  47,  51,  39],
        [  9,   9,   9, ...,  49,  56,  42]],

       [[237, 237, 237, ...,  62,  52,  48],
        [237, 237, 237, ...,  71,  54,  37],
        [236, 236, 236, ...,  61,  42,  47],
        ...,
        [  7,   7,   7, ..., 106, 105,  95],
        [  7,   7,   7, ..., 102, 106,  94],
        [  7,   7,   7, ..., 104, 111,  97]],

       [[220, 220, 220, ...,  56,  46,  42],
        [220, 220, 220, ...,  65,  48,  31],
        [219, 219, 219, ...,  55,  36,  41],
        ...,
        [  6,   6,   6, ..., 101, 100,  91],
        [  6,   6,   6, ...,  99, 104,  92],
        [  6,   6,   6, ..., 103, 110,  96]]], dtype=uint8)